package com.example.demo.service;

import com.example.demo.dto.PurchaseOrderRequest;
import com.example.demo.dto.PurchaseOrderResponse;
import com.example.demo.entity.*;
import com.example.demo.enums.PurchaseOrderStatus;
import com.example.demo.exception.BadRequestException;
import com.example.demo.exception.ResourceNotFoundException;
import com.example.demo.repository.*;
import com.example.demo.util.SecurityUtils;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.*;
import java.util.stream.Collectors;

@Service
@Transactional
public class PurchaseOrderService {

    private static final Logger log = LoggerFactory.getLogger(PurchaseOrderService.class);

    @Autowired
    private PurchaseOrderRepository purchaseOrderRepository;

    @Autowired
    private SupplierRepository supplierRepository;

    @Autowired
    private SupplierProductRepository supplierProductRepository;

    @Autowired
    private ProductRepository productRepository;

    @Autowired
    private OrganizationRepository organizationRepository;

    @Autowired
    private NotificationService notificationService;

    public PurchaseOrderResponse createPurchaseOrder(PurchaseOrderRequest request) {
        Long organizationId = SecurityUtils.getCurrentUserOrganizationId();

        Organization organization = organizationRepository.findById(organizationId)
                .orElseThrow(() -> new ResourceNotFoundException("Organization not found"));

        Supplier supplier = supplierRepository.findByIdAndOrganizationId(request.getSupplierId(), organizationId)
                .orElseThrow(() -> new ResourceNotFoundException("Supplier", "id", request.getSupplierId()));

        PurchaseOrder po = PurchaseOrder.builder()
                .poNumber(generatePoNumber())
                .status(PurchaseOrderStatus.DRAFT)
                .organization(organization)
                .supplier(supplier)
                .expectedDeliveryDate(request.getExpectedDeliveryDate())
                .notes(request.getNotes())
                .isAutoGenerated(false)
                .build();

        for (PurchaseOrderRequest.PurchaseOrderItemRequest itemReq : request.getItems()) {
            Product product = productRepository.findByIdAndOrganizationId(itemReq.getProductId(), organizationId)
                    .orElseThrow(() -> new ResourceNotFoundException("Product", "id", itemReq.getProductId()));

            PurchaseOrderItem item = PurchaseOrderItem.builder()
                    .product(product)
                    .quantity(itemReq.getQuantity())
                    .unitPrice(itemReq.getUnitPrice())
                    .build();

            po.addItem(item);
        }

        po.calculateTotalAmount();
        PurchaseOrder savedPo = purchaseOrderRepository.save(po);
        return mapToResponse(savedPo);
    }

    @Transactional(readOnly = true)
    public PurchaseOrderResponse getPurchaseOrderById(Long id) {
        Long organizationId = SecurityUtils.getCurrentUserOrganizationId();
        PurchaseOrder po = purchaseOrderRepository.findByIdAndOrganizationId(id, organizationId)
                .orElseThrow(() -> new ResourceNotFoundException("PurchaseOrder", "id", id));
        return mapToResponse(po);
    }

    @Transactional(readOnly = true)
    public Page<PurchaseOrderResponse> getAllPurchaseOrders(Pageable pageable) {
        Long organizationId = SecurityUtils.getCurrentUserOrganizationId();
        Page<PurchaseOrder> pos = purchaseOrderRepository.findByOrganizationId(organizationId, pageable);
        return pos.map(this::mapToResponse);
    }

    @Transactional(readOnly = true)
    public Page<PurchaseOrderResponse> getPurchaseOrdersByStatus(PurchaseOrderStatus status, Pageable pageable) {
        Long organizationId = SecurityUtils.getCurrentUserOrganizationId();
        Page<PurchaseOrder> pos = purchaseOrderRepository.findByOrganizationIdAndStatus(organizationId, status, pageable);
        return pos.map(this::mapToResponse);
    }

    public PurchaseOrderResponse approvePurchaseOrder(Long id) {
        Long organizationId = SecurityUtils.getCurrentUserOrganizationId();
        PurchaseOrder po = purchaseOrderRepository.findByIdAndOrganizationId(id, organizationId)
                .orElseThrow(() -> new ResourceNotFoundException("PurchaseOrder", "id", id));

        if (po.getStatus() != PurchaseOrderStatus.DRAFT && po.getStatus() != PurchaseOrderStatus.PENDING_APPROVAL) {
            throw new BadRequestException("Only DRAFT or PENDING_APPROVAL POs can be approved");
        }

        po.setStatus(PurchaseOrderStatus.APPROVED);
        PurchaseOrder savedPo = purchaseOrderRepository.save(po);

        notifyApproval(savedPo);
        return mapToResponse(savedPo);
    }

    public PurchaseOrderResponse cancelPurchaseOrder(Long id) {
        Long organizationId = SecurityUtils.getCurrentUserOrganizationId();
        PurchaseOrder po = purchaseOrderRepository.findByIdAndOrganizationId(id, organizationId)
                .orElseThrow(() -> new ResourceNotFoundException("PurchaseOrder", "id", id));

        if (po.getStatus() == PurchaseOrderStatus.RECEIVED || po.getStatus() == PurchaseOrderStatus.CANCELLED) {
            throw new BadRequestException("Cannot cancel a received or already cancelled PO");
        }

        po.setStatus(PurchaseOrderStatus.CANCELLED);
        PurchaseOrder savedPo = purchaseOrderRepository.save(po);
        return mapToResponse(savedPo);
    }

    public PurchaseOrderResponse receivePurchaseOrder(Long id) {
        Long organizationId = SecurityUtils.getCurrentUserOrganizationId();
        PurchaseOrder po = purchaseOrderRepository.findByIdAndOrganizationId(id, organizationId)
                .orElseThrow(() -> new ResourceNotFoundException("PurchaseOrder", "id", id));

        if (po.getStatus() != PurchaseOrderStatus.ORDERED && po.getStatus() != PurchaseOrderStatus.APPROVED) {
            throw new BadRequestException("Only APPROVED or ORDERED POs can be marked as received");
        }

        po.setStatus(PurchaseOrderStatus.RECEIVED);

        // Restore stock for each item
        for (PurchaseOrderItem item : po.getItems()) {
            Product product = item.getProduct();
            product.restoreStock(item.getQuantity());
            productRepository.save(product);
        }

        PurchaseOrder savedPo = purchaseOrderRepository.save(po);
        return mapToResponse(savedPo);
    }

    public void generateAutoReorderPurchaseOrders() {
        log.info("Starting auto-reorder PO generation");

        List<Organization> orgs = organizationRepository.findAll();

        for (Organization org : orgs) {
            try {
                generateReorderForOrganization(org.getId());
            } catch (Exception ex) {
                log.error("Failed to generate reorder POs for org {}", org.getId(), ex);
            }
        }
    }

    private void generateReorderForOrganization(Long organizationId) {
        List<Product> lowStockProducts = productRepository.findLowStockProducts(organizationId);

        Map<Long, List<Product>> supplierMap = new HashMap<>();

        for (Product product : lowStockProducts) {
            List<SupplierProduct> supplierProducts = supplierProductRepository.findByProductId(product.getId());

            if (supplierProducts.isEmpty()) {
                log.warn("Product {} has no suppliers; skipping auto-reorder", product.getId());
                continue;
            }

            SupplierProduct preferredSupplier = supplierProducts.stream()
                    .filter(sp -> sp.getIsAvailable())
                    .max(Comparator.comparing(sp -> sp.getSupplier().getReliabilityScore() != null 
                            ? sp.getSupplier().getReliabilityScore() 
                            : BigDecimal.ZERO))
                    .orElse(supplierProducts.get(0));

            Supplier supplier = preferredSupplier.getSupplier();
            supplierMap.computeIfAbsent(supplier.getId(), k -> new ArrayList<>()).add(product);
        }

        for (Map.Entry<Long, List<Product>> entry : supplierMap.entrySet()) {
            Long supplierId = entry.getKey();
            List<Product> products = entry.getValue();

            try {
                createAutoReorderPurchaseOrder(organizationId, supplierId, products);
            } catch (Exception ex) {
                log.error("Failed to create auto-reorder PO for supplier {} in org {}", supplierId, organizationId, ex);
            }
        }
    }

    private void createAutoReorderPurchaseOrder(Long organizationId, Long supplierId, List<Product> products) {
        Supplier supplier = supplierRepository.findByIdAndOrganizationId(supplierId, organizationId)
                .orElseThrow(() -> new ResourceNotFoundException("Supplier", "id", supplierId));

        Organization org = organizationRepository.findById(organizationId)
                .orElseThrow(() -> new ResourceNotFoundException("Organization not found"));

        PurchaseOrder po = PurchaseOrder.builder()
                .poNumber(generatePoNumber())
                .status(PurchaseOrderStatus.PENDING_APPROVAL)
                .organization(org)
                .supplier(supplier)
                .expectedDeliveryDate(LocalDateTime.now().plusDays(supplier.getLeadTimeDays()))
                .isAutoGenerated(true)
                .notes("Auto-generated reorder PO for low-stock products")
                .build();

        for (Product product : products) {
            SupplierProduct sp = supplierProductRepository.findBySupplierIdAndProductId(supplierId, product.getId())
                    .orElseThrow(() -> new ResourceNotFoundException("SupplierProduct not found"));

            Integer reorderQty = Math.max(
                    supplier.getMinimumOrderQuantity(),
                    (int) Math.ceil(product.getLowStockThreshold() * 1.5)
            );

            PurchaseOrderItem item = PurchaseOrderItem.builder()
                    .product(product)
                    .quantity(reorderQty)
                    .unitPrice(sp.getCostPrice())
                    .build();

            po.addItem(item);
        }

        po.calculateTotalAmount();
        PurchaseOrder savedPo = purchaseOrderRepository.save(po);

        notifyAutoReorder(savedPo);
    }

    private void notifyAutoReorder(PurchaseOrder po) {
        try {
            String message = String.format(
                    "Auto-generated PO %s created for %s with %d items. Total: %s",
                    po.getPoNumber(),
                    po.getSupplier().getName(),
                    po.getItems().size(),
                    po.getTotalAmount()
            );

            List<User> admins = new ArrayList<>();
            // In production, fetch admin users from DB
            for (User admin : admins) {
                notificationService.createNotification(
                        admin,
                        po.getOrganization(),
                        Notification.NotificationType.SYSTEM_ALERT,
                        "Auto-Reorder PO Created",
                        message,
                        Notification.Priority.MEDIUM,
                        Notification.RelatedEntityType.ORDER,
                        po.getId()
                );
            }
        } catch (Exception ex) {
            log.warn("Failed to send auto-reorder notification", ex);
        }
    }

    private void notifyApproval(PurchaseOrder po) {
        try {
            String message = String.format(
                    "PO %s has been approved. Supplier: %s, Total: %s",
                    po.getPoNumber(),
                    po.getSupplier().getName(),
                    po.getTotalAmount()
            );

            List<User> admins = new ArrayList<>();
            for (User admin : admins) {
                notificationService.createNotification(
                        admin,
                        po.getOrganization(),
                        Notification.NotificationType.SYSTEM_ALERT,
                        "PO Approved",
                        message,
                        Notification.Priority.MEDIUM,
                        Notification.RelatedEntityType.ORDER,
                        po.getId()
                );
            }
        } catch (Exception ex) {
            log.warn("Failed to send PO approval notification", ex);
        }
    }

    private String generatePoNumber() {
        return "PO-" + System.currentTimeMillis() + "-" + UUID.randomUUID().toString().substring(0, 8).toUpperCase();
    }

    private PurchaseOrderResponse mapToResponse(PurchaseOrder po) {
        List<PurchaseOrderResponse.PurchaseOrderItemResponse> items = po.getItems().stream()
                .map(item -> PurchaseOrderResponse.PurchaseOrderItemResponse.builder()
                        .id(item.getId())
                        .productId(item.getProduct().getId())
                        .productName(item.getProduct().getName())
                        .productSku(item.getProduct().getSku())
                        .quantity(item.getQuantity())
                        .unitPrice(item.getUnitPrice())
                        .subtotal(item.getSubtotal())
                        .build())
                .collect(Collectors.toList());

        return PurchaseOrderResponse.builder()
                .id(po.getId())
                .poNumber(po.getPoNumber())
                .status(po.getStatus())
                .organizationId(po.getOrganization().getId())
                .supplierId(po.getSupplier().getId())
                .supplierName(po.getSupplier().getName())
                .totalAmount(po.getTotalAmount())
                .expectedDeliveryDate(po.getExpectedDeliveryDate())
                .notes(po.getNotes())
                .isAutoGenerated(po.getIsAutoGenerated())
                .items(items)
                .createdAt(po.getCreatedAt())
                .updatedAt(po.getUpdatedAt())
                .build();
    }
}
