import { useState } from 'react';
import { CheckCircle, XCircle, Package, AlertCircle } from 'lucide-react';
import Table from '../../../components/common/Table';
import Pagination from '../../../components/common/Pagination';
import { usePermissions } from '../../../hooks/usePermissions';
import { useApprovePurchaseOrder, useReceivePurchaseOrder, useCancelPurchaseOrder } from '../hooks/usePurchaseOrderOperations';
import { formatCurrency, formatDateTime } from '../../../utils/formatters';

const statusBadgeConfig = {
  DRAFT: { bg: 'bg-gray-100', text: 'text-gray-800', label: 'Draft' },
  PENDING_APPROVAL: { bg: 'bg-blue-100', text: 'text-blue-800', label: 'Pending' },
  APPROVED: { bg: 'bg-green-100', text: 'text-green-800', label: 'Approved' },
  ORDERED: { bg: 'bg-purple-100', text: 'text-purple-800', label: 'Ordered' },
  RECEIVED: { bg: 'bg-success-100', text: 'text-success-800', label: 'Received' },
  CANCELLED: { bg: 'bg-danger-100', text: 'text-danger-800', label: 'Cancelled' },
};

const PurchaseOrderList = ({ purchaseOrders, currentPage, totalPages, onPageChange, isLoading }) => {
  const { canEditProduct } = usePermissions();
  const approveMutation = useApprovePurchaseOrder();
  const receiveMutation = useReceivePurchaseOrder();
  const cancelMutation = useCancelPurchaseOrder();

  const handleApprove = (po) => {
    if (window.confirm(`Approve PO ${po.poNumber}?`)) {
      approveMutation.mutate(po.id);
    }
  };

  const handleReceive = (po) => {
    if (window.confirm(`Mark PO ${po.poNumber} as received? This will update stock levels.`)) {
      receiveMutation.mutate(po.id);
    }
  };

  const handleCancel = (po) => {
    if (window.confirm(`Cancel PO ${po.poNumber}?`)) {
      cancelMutation.mutate(po.id);
    }
  };

  const columns = [
    {
      header: 'PO Number',
      accessor: 'poNumber',
      render: (row) => (
        <div>
          <p className="font-medium text-gray-900">{row.poNumber}</p>
          {row.isAutoGenerated && (
            <span className="text-xs bg-blue-100 text-blue-800 px-2 py-1 rounded">Auto</span>
          )}
        </div>
      ),
    },
    {
      header: 'Supplier',
      accessor: 'supplierName',
      render: (row) => <span className="text-sm text-gray-600">{row.supplierName}</span>,
    },
    {
      header: 'Status',
      accessor: 'status',
      render: (row) => {
        const config = statusBadgeConfig[row.status];
        return (
          <span className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium ${config.bg} ${config.text}`}>
            {config.label}
          </span>
        );
      },
    },
    {
      header: 'Items',
      accessor: 'items',
      render: (row) => <span className="text-sm font-medium">{row.items?.length || 0}</span>,
    },
    {
      header: 'Total',
      accessor: 'totalAmount',
      render: (row) => <span className="font-medium">{formatCurrency(row.totalAmount)}</span>,
    },
    {
      header: 'Expected Delivery',
      accessor: 'expectedDeliveryDate',
      render: (row) => (
        <span className="text-sm text-gray-600">
          {row.expectedDeliveryDate ? formatDateTime(row.expectedDeliveryDate) : 'N/A'}
        </span>
      ),
    },
    {
      header: 'Actions',
      accessor: 'id',
      render: (row) =>
        canEditProduct && (
          <div className="flex items-center gap-2">
            {(row.status === 'DRAFT' || row.status === 'PENDING_APPROVAL') && (
              <button
                onClick={() => handleApprove(row)}
                className="p-2 text-success-600 hover:bg-success-50 rounded-lg transition-colors"
                title="Approve"
                disabled={approveMutation.isPending}
              >
                <CheckCircle className="h-4 w-4" />
              </button>
            )}
            {(row.status === 'APPROVED' || row.status === 'ORDERED') && (
              <button
                onClick={() => handleReceive(row)}
                className="p-2 text-primary-600 hover:bg-primary-50 rounded-lg transition-colors"
                title="Receive"
                disabled={receiveMutation.isPending}
              >
                <Package className="h-4 w-4" />
              </button>
            )}
            {row.status !== 'RECEIVED' && row.status !== 'CANCELLED' && (
              <button
                onClick={() => handleCancel(row)}
                className="p-2 text-danger-600 hover:bg-danger-50 rounded-lg transition-colors"
                title="Cancel"
                disabled={cancelMutation.isPending}
              >
                <XCircle className="h-4 w-4" />
              </button>
            )}
          </div>
        ),
    },
  ];

  return (
    <>
      <Table
        columns={columns}
        data={purchaseOrders}
        loading={isLoading}
        emptyMessage="No purchase orders found."
      />

      {totalPages > 1 && (
        <div className="mt-6">
          <Pagination
            currentPage={currentPage}
            totalPages={totalPages}
            onPageChange={onPageChange}
          />
        </div>
      )}
    </>
  );
};

export default PurchaseOrderList;
