package com.example.demo.dto;

import com.example.demo.enums.PurchaseOrderStatus;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.List;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class PurchaseOrderResponse {

    private Long id;

    private String poNumber;

    private PurchaseOrderStatus status;

    private Long organizationId;

    private Long supplierId;

    private String supplierName;

    private BigDecimal totalAmount;

    private LocalDateTime expectedDeliveryDate;

    private String notes;

    private Boolean isAutoGenerated;

    private List<PurchaseOrderItemResponse> items;

    private LocalDateTime createdAt;

    private LocalDateTime updatedAt;

    @Data
    @NoArgsConstructor
    @AllArgsConstructor
    @Builder
    public static class PurchaseOrderItemResponse {

        private Long id;

        private Long productId;

        private String productName;

        private String productSku;

        private Integer quantity;

        private BigDecimal unitPrice;

        private BigDecimal subtotal;
    }
}
